volumes:
  db-data:
  redis-data:

services:
  server:
    build:
      context: .
      target: development # Stage "development"
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
  db:
    image: postgres:17.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:7.4.1
    restart: unless-stopped
    command: [
      "redis-server",
      "--requirepass", "${REDIS_PASSWORD}",
      "--appendonly", "yes"
    ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    networks:
        - internal

networks:
  internal: